// ===== 9. ROTATE - 도형 회전 =====
let rotScore,rotRound,rotTime;
function initRotate(){rotScore=0;rotRound=0;rotTime=30;initHearts('rot');
document.getElementById('rot-round').textContent='30s';
clearInterval(curTimer);setTickFn(rotTick);curTimer=setInterval(rotTick,1000);rotNext()}
function rotTick(){rotTime--;document.getElementById('rot-round').textContent=rotTime+'s';if(rotTime<=10)document.getElementById('rot-round').className='g-timer urgent';if(rotTime<=0){clearInterval(curTimer);setTimeExtendResumeCallback((s)=>{rotTime=s;document.getElementById('rot-round').textContent=rotTime+'s';document.getElementById('rot-round').className='g-timer';curTimer=setInterval(rotTick,1000);rotNext()});showResult(rotScore,'도형 회전',[], {_isTimerEnd:true})}}
function rotNext(){rotRound++;setScore('rot-score',rotScore);const shape=[],bc=rotRound<=3?3:rotRound<=6?~~(Math.random()*2)+3:~~(Math.random()*3)+3;while(shape.length<bc){const x=~~(Math.random()*4),y=~~(Math.random()*4);if(!shape.some(b=>b.x===x&&b.y===y))shape.push({x,y})}const colors=['#3182F6','#8B5CF6','#EC4899','#F59E0B','#10B981'],color=colors[~~(Math.random()*colors.length)];document.getElementById('rot-original').innerHTML='';document.getElementById('rot-original').appendChild(drawShape(shape,color,100));const rots=[0,90,180,270],cr=rotRound<=3?90:rotRound<=6?rots[~~(Math.random()*2)+1]:rots[~~(Math.random()*3)+1],cs=rotShape(shape,cr),ms=shape.map(b=>({x:3-b.x,y:b.y}));let opts=[{shape:cs,correct:true},{shape:rotShape(ms,cr),correct:false}];const or=rots.filter(r=>r!==cr&&r!==0)[0]||90;opts.push({shape:rotShape(shape,or===cr?180:or),correct:false},{shape:rotShape(ms,or),correct:false});opts=opts.slice(0,4).sort(()=>Math.random()-.5);const od=document.getElementById('rot-opts');od.innerHTML='';opts.forEach(o=>{const w=document.createElement('div');w.className='rotate-opt';w.appendChild(drawShape(o.shape,color,200));w.onclick=()=>{if(w.classList.contains('ok')||w.classList.contains('no'))return;if(o.correct){w.classList.add('ok');rotScore+=10;setScore('rot-score',rotScore)}else{w.classList.add('no');od.querySelectorAll('.rotate-opt').forEach((el,j)=>{if(opts[j].correct)el.classList.add('ok')});curScore=rotScore;setHeartResumeCallback(rotNext);if(loseHeart('rot'))return}scheduleNextQuestion(rotNext,800)};od.appendChild(w)});document.getElementById('rot-q').textContent=`이 도형을 ${cr}° 회전하면?`}
function drawShape(bl,c,s){const cv=document.createElement('canvas');cv.width=s;cv.height=s;const ctx=cv.getContext('2d'),bs=s/4;bl.forEach(b=>{ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(b.x*bs+2,b.y*bs+2,bs-4,bs-4,4);ctx.fill()});return cv}
function rotShape(bl,d){const t=((d%360)+360)%360/90;let b=bl.map(x=>({...x}));for(let i=0;i<t;i++)b=b.map(x=>({x:3-x.y,y:x.x}));return b}
