// ===== 4. STROOP - 색깔 맞추기 =====
let stroopScore,stroopTime,stroopTotal,stroopCombo;
const COLORS=[{name:'빨강',hex:'#F04452'},{name:'파랑',hex:'#3182F6'},{name:'초록',hex:'#1FC58E'},{name:'노랑',hex:'#F59E0B'},{name:'보라',hex:'#8B5CF6'}];
function initStroop(){stroopScore=0;stroopTime=30;stroopTotal=0;stroopCombo=0;document.getElementById('stroop-score').textContent='0점';clearInterval(curTimer);initHearts('stroop');document.getElementById('stroop-timer').textContent='30s';document.getElementById('stroop-timer').className='g-timer';setTickFn(stroopTick);curTimer=setInterval(stroopTick,1000);stroopGen()}
function stroopTick(){stroopTime--;document.getElementById('stroop-timer').textContent=stroopTime+'s';if(stroopTime<=10)document.getElementById('stroop-timer').className='g-timer urgent';if(stroopTime<=0){clearInterval(curTimer);setTimeExtendResumeCallback((s)=>{stroopTime=s;document.getElementById('stroop-timer').textContent=stroopTime+'s';document.getElementById('stroop-timer').className='g-timer';curTimer=setInterval(stroopTick,1000);stroopGen()});showResult(stroopScore,'색깔 맞추기',[{val:stroopTotal,label:'문제 수'},{val:stroopCombo+'x',label:'최대 콤보'}], {_isTimerEnd: true})}}
function stroopGen(){const wc=COLORS[~~(Math.random()*COLORS.length)];let dc;do{dc=COLORS[~~(Math.random()*COLORS.length)]}while(dc===wc&&Math.random()>.3);document.getElementById('stroop-word').textContent=wc.name;document.getElementById('stroop-word').style.color=dc.hex;let opts=[dc];while(opts.length<4){const c=COLORS[~~(Math.random()*COLORS.length)];if(!opts.includes(c))opts.push(c)}opts.sort(()=>Math.random()-.5);document.getElementById('stroop-opts').innerHTML=opts.map(o=>`<button class="stroop-opt" style="color:${o.hex}" onclick="stroopPick('${o.name}','${dc.name}')">${o.name}</button>`).join('')}
function stroopPick(p,c){stroopTotal++;if(p===c){stroopCombo++;const bonus=stroopCombo>=10?3:stroopCombo>=5?2:1;stroopScore+=10*bonus;
setScore('stroop-score',stroopScore);if(stroopCombo>=5){stroopTime=Math.min(stroopTime+2,99);toast(stroopCombo+'콤보! +2초')}}
else{stroopCombo=0;curScore=stroopScore;setHeartResumeCallback(stroopGen);if(loseHeart('stroop'))return}stroopGen()}
